---

- hosts: all
  connection: local
  gather_facts: no
  vars_prompt:
    - name: username
      prompt: "Enter username"
      private: no

    - name: password
      prompt: "Enter password"
      private: yes
      confirm: yes
  tasks:
    - name: network_triage
      command: python network_triage.py "{{ ansible_host }}" "{{ port }}" "{{ username }}" "{{ password }}"
      no_log: true
      register: python_output

    - debug:
        var: python_output.stdout_lines
