---
InterfaceTable:
  get: interfaces/interface
  view: InterfaceView
InterfaceView:
  fields:     
    ifname: name
    unit: unit
    etherlag: ether-options/ieee-802.3ad
    gigetherlag: gigether-options/ieee-802.3ad
